apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-app: etcd-server
  name: etcd-server
  namespace: kube-system
spec:
  priorityClassName: system-node-critical
  containers:
  - name: etcd-container
    command:
    - /bin/sh
    - -c
    - mkfifo /tmp/pipe; (tee -a /var/log/etcd.log < /tmp/pipe & ) ;
      exec /usr/local/bin/etcd  > /tmp/pipe 2>&1
    env:
    - name: ETCD_NAME
      value: etcd_master_name
    - name: ETCD_DATA_DIR
      value: /var/etcd/data
    - name: ETCD_LOG_LEVEL
      value: info
    - name: ETCD_LOG_OUTPUTS
      value: stdout
    - name: ETCD_LISTEN_PEER_URLS
      value: https://INTERNAL_IP:2380
    - name: ETCD_LISTEN_CLIENT_URLS
      value: https://INTERNAL_IP:4001,https://127.0.0.1:4001
    - name: ETCD_ADVERTISE_CLIENT_URLS
      value: https://INTERNAL_IP:4001
    - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
      value: https://INTERNAL_IP:2380
    - name: ETCD_INITIAL_CLUSTER_STATE
      value: new
    - name: ETCD_INITIAL_CLUSTER_TOKEN
      value: etcd-cluster-token-etcd
    - name: ETCD_INITIAL_CLUSTER
      value: master-0=https://KUBERNETES_ADDRESS_0:2380,master-1=https://KUBERNETES_ADDRESS_1:2380,master-2=https://KUBERNETES_ADDRESS_2:2380
    - name: ETCD_PEER_CERT_FILE
      value: /opt/kubernetes/certificates/kubernetes.pem
    - name: ETCD_PEER_KEY_FILE
      value: /opt/kubernetes/certificates/kubernetes-key.pem
    - name: ETCD_PEER_TRUSTED_CA_FILE
      value: /opt/kubernetes/certificates/ca.pem
    - name: ETCD_PEER_CLIENT_CERT_AUTH
      value: 'True'
    - name: ETCD_CLIENT_CERT_AUTH
      value: 'True'
    - name: ETCD_CERT_FILE
      value: /opt/kubernetes/certificates/kubernetes.pem
    - name: ETCD_KEY_FILE
      value: /opt/kubernetes/certificates/kubernetes-key.pem
    - name: ETCD_TRUSTED_CA_FILE
      value: /opt/kubernetes/certificates/ca.pem
    image: gcr.io/etcd-development/etcd:v3.4.1
    # livenessProbe:
    #   FailureThreshold: 8
    #   exec:
    #     command:
    #     - /bin/sh
    #     - -ec
    #     - etcdctl --endpoints=127.0.0.1:4001 --cacert=/opt/kubernetes/certificates/ca.pem
    #       --key=/opt/kubernetes/certificates/etcd-client-key.pem --cert=/opt/kubernetes/certificates/etcd-client.pem
    #       endpoint health
    #   initialDelaySeconds: 45
    #   timeoutSeconds: 15
    ports:
    - containerPort: 4001
      hostPort: 4001
      name: serverport
    - containerPort: 2380
      hostPort: 2380
      name: clientport
    # resources:
    #   requests:
    #     cpu: 100m 
    #     memory: 500Mi
    #   limits:
    #     cpu: 100m 
    #     memory: 500Mi
    volumeMounts:
    - mountPath: /var/etcd/data
      name: varetcddata
    - mountPath: /var/log/etcd.log
      name: varlogetcd
    - mountPath: /opt/kubernetes
      name: optkubernetes
    - mountPath: /etc/hosts
      name: hosts
      readOnly: true
  hostNetwork: true
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  volumes:
  - hostPath:
      path: /var/etcd/data
    name: varetcddata
  - hostPath:
      path: /var/log/etcd.log
      type: FileOrCreate
    name: varlogetcd
  - hostPath:
      path: /etc/hosts
    name: hosts
  - hostPath:
      path: /opt/kubernetes
    name: optkubernetes
